name: gr_snarfer_env 
channels:
  - conda-forge
dependencies:
  - python=3.11
#  - pandas
#  - numpy
  - selenium = 4.9.0
  - beautifulsoup4 = 4.12.2
  - lxml = 4.9.2
  - pandas = 2.0.1
  - regex = 2023.5.5
  - webdriver-manager = 3.8.6
  - mypy = 1.2.0
